// Expand Workspace, strategist consult, & metrics for AI-OS (Fully Frontend Static)
// Powered by A.R. Labs

import { state } from './core.js';
import { showToast } from './utils.js';
import { apiCall } from './apiClient.js';
import { isUserAuthenticated } from './auth.js';
import { showPricingModal } from './ui.js';
import { loadLiveBusinessNews } from './tutorials.js';

export function updateConversionFunnel(modelData, budgetValue) {
  const trafficEl = document.getElementById('funnel-traffic');
  const qualifiedEl = document.getElementById('funnel-qualified');
  const conversionsEl = document.getElementById('funnel-conversions');
  const growthEl = document.getElementById('funnel-growth');

  const barTraffic = document.getElementById('funnel-bar-traffic');
  const barQualified = document.getElementById('funnel-bar-qualified');
  const barConversions = document.getElementById('funnel-bar-conversions');
  const barGrowth = document.getElementById('funnel-bar-growth');

  const budget = parseFloat(budgetValue) || 0;
  
  let traffic = 1500;
  let qualified = 450;
  let conversions = 20;
  
  if (modelData) {
    const baseRev = parseFloat(modelData.expectedRevenue || '0') || 50000;
    const baseUsers = parseFloat(modelData.targetUsers || '0') || 1000;
    
    traffic = Math.round(baseUsers * (1 + (budget / 5000)));
    qualified = Math.round(traffic * 0.32);
    conversions = Math.round(qualified * 0.08);
  }
  
  const cpi = budget === 0 ? 0.0 : (budget / qualified);
  const convRate = traffic === 0 ? 0.0 : (conversions / traffic);

  if (trafficEl) trafficEl.textContent = traffic.toLocaleString('en-IN');
  if (qualifiedEl) qualifiedEl.textContent = qualified.toLocaleString('en-IN');
  if (conversionsEl) conversionsEl.textContent = conversions.toLocaleString('en-IN');
  if (growthEl) growthEl.textContent = `₹${cpi.toFixed(1)} / lead`;

  if (barTraffic) barTraffic.style.setProperty('--w', '100%');
  if (barQualified) barQualified.style.setProperty('--w', '70%');
  if (barConversions) barConversions.style.setProperty('--w', `${Math.min(100, Math.max(10, convRate * 10 * 100))}%`);
  if (barGrowth) {
    barGrowth.style.setProperty('--w', budget === 0 ? '20%' : (budget <= 5000 ? '55%' : '90%'));
  }
}

function getMockStrategy(name, audience, bottleneck) {
  const lowBottleneck = bottleneck.toLowerCase();
  
  let analysis = `Based on our static audit of <strong>${name}</strong> targeting <strong>${audience}</strong>, we have identified a key friction point relating to <em>"${bottleneck}"</em>. Your organic reach is insufficient to sustain inbound interest, resulting in high customer acquisition costs. We suggest introducing automated webhook tracking to monitor checkout drop-offs instantly.`;
  let opportunities = `1. **Programmatic Outbound Directory**: Launch a regional listing template linking local dentists to <strong>${name}</strong>'s API.<br>2. **Automated Audits**: Use Loom video pitches to show prospects how custom bots recover 30% of cart abandonment.<br>3. **Trigger-Based CRM Syncs**: Configure Stripe webhook triggers to instantly update client records in Google Sheets.`;
  let automation = `Trigger: Stripe Charge Capture --> Action: Pass user metadata to OpenAI Assistants API --> Action: Draft customized welcome agreement pdf --> Action: Trigger email delivery with sign-off link via Resend.`;
  let marketing = `Direct outbound outreach targeting 30 corporate directors daily. Leverage customized, brief introductory Loom audit screen recordings highlighting how <strong>${name}</strong> solves their acquisition delays.`;
  let leads = `Scrape list of regional companies with >₹5M annual turnovers. Set up Instantly.ai email sequencing campaigns targeting 40 new prospects daily. Target open rates >55% and positive reply rates >7%.`;
  let revenue = `Decline hourly pricing packages in favor of monthly outcomes. Introduce a setup integration retainer of ₹60,000, plus a flat 10% commission on all completed checkout transactions generated by your pipeline.`;
  let plan = `<strong>Days 1-30 (Launch Phase)</strong>:<br>- Setup portfolio deck presenting your client value proposition.<br>- Construct target company lists matching niche categories.<br><br><strong>Days 31-60 (Scale Phase)</strong>:<br>- Initiate Instantly outbound mail sequences contacting 30 targets daily.<br>- Conduct short video site audits for warm responses.<br><br><strong>Days 61-90 (Optimization Phase)</strong>:<br>- Close 3 retainers.<br>- Deploy maintenance support agreements and cross-sell system extensions.`;

  if (lowBottleneck.includes('traffic') || lowBottleneck.includes('leads') || lowBottleneck.includes('visitor')) {
    analysis = `Traffic challenges for <strong>${name}</strong> indicate a lack of distribution channels. Relying on paid ads is inefficient for targeting <strong>${audience}</strong>. Organic short-form content funnels and Programmatic SEO listings represent the highest return-on-investment pathways.`;
    opportunities = `1. **Short Video Funnels**: Record 60-second value checklists explaining 'How ${audience} lose leads'.<br>2. **Dynamic Search Directories**: Construct SEO-optimized landing pages targeting regional keywords.`;
    marketing = `Establish organic lead magnets. Host checklist guides on notion boards and link them inside short-video captions.`;
  } else if (lowBottleneck.includes('conversion') || lowBottleneck.includes('sell') || lowBottleneck.includes('sales')) {
    analysis = `Conversion drops for <strong>${name}</strong> mean poor trust positioning or bad offer frameworks. Structuring a clear zero-risk guarantee (e.g. 'Only pay for captured leads') increases signups with <strong>${audience}</strong>.`;
    opportunities = `Integrate interactive conversational chats directly on prospect landing sites to answer customer questions in under 10 seconds.`;
    automation = `Trigger: User submits query in Chatbox --> Action: Parse via Llama 3 on Groq API --> Action: Send Slack alert to sales agent with lead contact details.`;
  }

  return {
    analysis,
    opportunities,
    automation,
    marketing,
    leads,
    revenue,
    plan
  };
}

function formatINR(num) {
  if (num === undefined || num === null) return 'N/A';
  return '₹' + Number(num).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
}

export async function loadLiveDashboardMetrics() {
  const loadingEl = document.getElementById('market-data-loading');
  const errorEl = document.getElementById('market-data-error');
  const contentEl = document.getElementById('market-data-content');
  const tbody = document.getElementById('market-data-tbody');
  
  if (!tbody) return;

  // Show loading state initially
  if (loadingEl && loadingEl.style.display !== 'block') {
    loadingEl.style.display = 'block';
    if (errorEl) errorEl.style.display = 'none';
    if (contentEl) contentEl.style.display = 'none';
  }

  try {
    const data = await apiCall('/api/market/quotes');
    if (!data || !data.success || !data.quotes) {
      throw new Error("Invalid response or quotes data missing");
    }

    const { quotes, usdInrRate, timestamp } = data;
    let html = '';

    const assetConfig = [
      { key: 'NIFTY', name: 'NIFTY 50' },
      { key: 'NASDAQ', name: 'NASDAQ*' },
      { key: 'NVDA', name: 'NVDA (NVIDIA)*' },
      { key: 'BTC', name: 'BTC (Bitcoin)*' },
      { key: 'Gold', name: 'Gold*' }
    ];

    assetConfig.forEach(cfg => {
      const q = quotes[cfg.key];
      if (q) {
        const priceStr = formatINR(q.priceINR);
        const changeVal = q.changeINR;
        const pctVal = q.percentChange;
        
        const sign = changeVal >= 0 ? '+' : '';
        const color = changeVal >= 0 ? '#00D084' : '#ff4a4a';
        const changeStr = `${sign}${changeVal.toFixed(2)}`;
        const pctStr = `${sign}${pctVal.toFixed(2)}%`;

        html += `
          <tr>
            <td style="font-family: var(--font-mono); color: #fff;">${cfg.name}</td>
            <td style="font-family: var(--font-mono); text-align: right; color: #fff;">${priceStr}</td>
            <td style="font-family: var(--font-mono); text-align: right; color: ${color};">${changeStr} (${pctStr})</td>
          </tr>
        `;
      } else {
        html += `
          <tr>
            <td style="font-family: var(--font-mono); color: #fff;">${cfg.name}</td>
            <td style="font-family: var(--font-mono); text-align: right; color: var(--bus-text-muted);">Data Unavailable</td>
            <td style="font-family: var(--font-mono); text-align: right; color: var(--bus-text-muted);">N/A</td>
          </tr>
        `;
      }
    });

    tbody.innerHTML = html;

    // Render footer details
    let footerEl = document.getElementById('market-data-footer');
    if (!footerEl) {
      footerEl = document.createElement('div');
      footerEl.id = 'market-data-footer';
      footerEl.style.cssText = 'margin-top: 12px; font-size: 0.72rem; color: var(--bus-text-secondary); font-family: var(--font-mono); line-height: 1.4; display: flex; flex-direction: column; gap: 2px; border-top: 1px solid var(--bus-border); padding-top: 10px;';
      contentEl.appendChild(footerEl);
    }

    const formattedTime = new Date(timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
    footerEl.innerHTML = `
      <span>* Converted from USD. Rate: 1 USD = ₹${usdInrRate.toFixed(2)}</span>
      <span>Last Updated: ${formattedTime}</span>
    `;

    if (loadingEl) loadingEl.style.display = 'none';
    if (errorEl) errorEl.style.display = 'none';
    if (contentEl) contentEl.style.display = 'block';

  } catch (err) {
    console.error("[Live Market Metrics Load Error] Failed to retrieve live quote data:", err);
    if (loadingEl) loadingEl.style.display = 'none';
    if (errorEl) {
      errorEl.textContent = `Live market data temporarily unavailable: ${err.message}`;
      errorEl.style.display = 'block';
    }
  }
}

    // Render calendar metrics
    const calList = document.getElementById('calendar-events-list');
    if (calList) {
      calList.innerHTML = `
        <div class="calendar-item" style="background: rgba(255,255,255,0.01); border: 1px solid var(--bus-border); padding: 12px; border-radius: 6px; margin-bottom: 10px;">
          <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
            <strong style="color: var(--bus-primary); font-family: var(--font-mono); font-size: 0.78rem;">JUL 12</strong>
            <span style="font-size: 0.7rem; color: var(--bus-text-secondary);">MACRO EVENT</span>
          </div>
          <strong style="color: #fff; font-size: 0.85rem; font-weight: 600;">US CPI Inflation Release</strong>
          <span style="color: var(--bus-text-secondary); font-size: 0.75rem; display: block; margin-top: 2px;">Directly influences global interest rates & tech valuations</span>
        </div>
        <div class="calendar-item" style="background: rgba(255,255,255,0.01); border: 1px solid var(--bus-border); padding: 12px; border-radius: 6px; margin-bottom: 10px;">
          <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
            <strong style="color: var(--bus-primary); font-family: var(--font-mono); font-size: 0.78rem;">JUL 28</strong>
            <span style="font-size: 0.7rem; color: var(--bus-text-secondary);">EARNINGS</span>
          </div>
          <strong style="color: #fff; font-size: 0.85rem; font-weight: 600;">Big Tech Earnings Season</strong>
          <span style="color: var(--bus-text-secondary); font-size: 0.75rem; display: block; margin-top: 2px;">NVIDIA, Google, Microsoft report AI investment yields</span>
        </div>
      `;
    }

    // Render trends metrics
    const trendsCont = document.getElementById('trends-container');
    if (trendsCont) {
      trendsCont.innerHTML = `
        <div class="trend-item" style="margin-bottom: 12px;">
          <div class="trend-meta" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px;">
            <strong style="color: #fff; font-size: 0.85rem; font-weight: 600;">Programmatic SEO & Directories</strong>
            <span class="trend-growth" style="color: var(--bus-primary); font-family: var(--font-mono); font-size: 0.8rem; font-weight: 700;">+43.5% CAGR</span>
          </div>
          <p class="trend-desc" style="color: var(--bus-text-secondary); font-size: 0.78rem; line-height: 1.4; margin: 0;">AI-generated regional catalog sites driving zero-cost incoming lead lists.</p>
        </div>
        <div class="trend-item" style="border-top: 1px solid var(--bus-border); padding-top: 12px; margin-top: 12px;">
          <div class="trend-meta" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px;">
            <strong style="color: #fff; font-size: 0.85rem; font-weight: 600;">Generative Support Orchestration</strong>
            <span class="trend-growth" style="color: var(--bus-primary); font-family: var(--font-mono); font-size: 0.8rem; font-weight: 700;">+65.2% CAGR</span>
          </div>
          <p class="trend-desc" style="color: var(--bus-text-secondary); font-size: 0.78rem; line-height: 1.4; margin: 0;">Replacing manual support teams with LLM agent ticket resolution workflows.</p>
        </div>
      `;
    }

    if (loadingEl) loadingEl.style.display = 'none';
    if (errorEl) errorEl.style.display = 'none';
    if (contentEl) contentEl.style.display = 'block';

  } catch (err) {
    console.error("Dashboard live market data load failed:", err.message);
  }
}


export function initExpandSection() {
  const chatInput = document.getElementById('chat-strategist-input');
  const chatSendBtn = document.getElementById('btn-chat-strategist-send');
  const chatLogs = document.getElementById('chat-strategist-logs');
  const outputPanel = document.getElementById('strategist-tabs-panel');
  const btnAnalyze = document.getElementById('btn-strategist-analyze');
  
  const strategTabBtns = document.querySelectorAll('.strategist-tab-btn');
  strategTabBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const targetTab = btn.getAttribute('data-output-tab');
      
      strategTabBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      
      const panes = document.querySelectorAll('.strategist-tab-pane');
      panes.forEach(p => p.classList.remove('active'));
      const activePane = document.getElementById(`tab-out-${targetTab}`);
      if (activePane) activePane.classList.add('active');
    });
  });

  let isAnalysisComputed = false;
  let currentBusinessContext = {
    name: '',
    audience: '',
    bottleneck: '',
    strategy: null
  };
  let strategistChatHistory = [];

  function classifyIntent(text) {
    const lowercase = text.toLowerCase();
    const strategyKeywords = [
      'strategy', 'roadmap', 'plan', 'scale', 'scaling', 'bottleneck', 'growth',
      'revenue', 'competitor', 'market', 'business', 'pricing', 'monetize',
      'monetization', 'marketing', 'sales', 'funnel', 'customer', 'acquisition',
      'retention', 'churn', 'product', 'launch', 'mvp', 'validate', 'validation'
    ];
    const isStrategyRequested = strategyKeywords.some(keyword => lowercase.includes(keyword));
    if (isStrategyRequested) return 'strategy';

    const greetingKeywords = ['hello', 'hi', 'hey', 'greetings', 'yo', 'sup', 'morning', 'afternoon', 'evening'];
    const isGreeting = greetingKeywords.some(keyword => {
      const regex = new RegExp(`\\b${keyword}\\b`, 'i');
      return regex.test(lowercase);
    });
    if (isGreeting) return 'greeting';

    return 'casual';
  }

  if (chatInput && chatSendBtn) {
    const handleChatSend = async () => {
      const text = chatInput.value.trim();
      if (!text) return;
      
      if (!isUserAuthenticated()) {
        showToast("Please sign in to use the AI Strategist chat.", "warning");
        const authOverlay = document.getElementById('auth-modal-overlay');
        if (authOverlay) authOverlay.style.display = 'flex';
        return;
      }
      
      if (!isAnalysisComputed) {
        showToast("Please compile the Enterprise Matrix first.", "warning");
        return;
      }

      chatInput.value = '';
      
      const userBubble = document.createElement('div');
      userBubble.className = 'chat-bubble user';
      userBubble.innerHTML = `<div class="chat-bubble-text">${text}</div>`;
      chatLogs.appendChild(userBubble);
      chatLogs.scrollTop = chatLogs.scrollHeight;

      const typingBubble = document.createElement('div');
      typingBubble.className = 'chat-bubble assistant typing';
      typingBubble.innerHTML = `<div class="chat-bubble-text">⏳ Consultant is typing...</div>`;
      chatLogs.appendChild(typingBubble);
      chatLogs.scrollTop = chatLogs.scrollHeight;

      const intent = classifyIntent(text);
      if (intent === 'greeting') {
        typingBubble.remove();
        const reply = "Hello! I am your Elite Business Strategist. Let me know when you're ready to deconstruct your business strategy, roadmap, or scaling plans.";
        
        strategistChatHistory.push({ role: 'user', content: text });
        strategistChatHistory.push({ role: 'assistant', content: reply });

        const replyBubble = document.createElement('div');
        replyBubble.className = 'chat-bubble assistant';
        replyBubble.innerHTML = `<div class="chat-bubble-text">${reply}</div>`;
        chatLogs.appendChild(replyBubble);
        chatLogs.scrollTop = chatLogs.scrollHeight;
        return;
      }
      
      if (intent === 'casual') {
        typingBubble.remove();
        const reply = "I am a specialized Red-Team Business Strategist. Let's focus on strategy, roadmap, planning, or scaling to get the most value out of our session. What strategy or plan are we audit-testing today?";
        
        strategistChatHistory.push({ role: 'user', content: text });
        strategistChatHistory.push({ role: 'assistant', content: reply });

        const replyBubble = document.createElement('div');
        replyBubble.className = 'chat-bubble assistant';
        replyBubble.innerHTML = `<div class="chat-bubble-text">${reply}</div>`;
        chatLogs.appendChild(replyBubble);
        chatLogs.scrollTop = chatLogs.scrollHeight;
        return;
      }

      try {
        const responseData = await apiCall('/api/strategist/chat', {
          method: 'POST',
          body: JSON.stringify({
            userInput: text,
            history: strategistChatHistory
          })
        });

        typingBubble.remove();

        if (responseData.success) {
          const reply = responseData.reply;
          
          strategistChatHistory.push({ role: 'user', content: text });
          strategistChatHistory.push({ role: 'assistant', content: reply });

          const replyBubble = document.createElement('div');
          replyBubble.className = 'chat-bubble assistant';
          replyBubble.innerHTML = `<div class="chat-bubble-text">${reply}</div>`;
          chatLogs.appendChild(replyBubble);
          chatLogs.scrollTop = chatLogs.scrollHeight;
          
          if (responseData.quota) {
            showToast(`Remaining Daily Quota: ${responseData.quota.remaining}/${responseData.quota.limit}`, "info");
          }
        }
      } catch (err) {
        typingBubble.remove();
        console.error('[Strategist Chat Error]', err);
      }
    };

    chatSendBtn.addEventListener('click', handleChatSend);
    chatInput.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') handleChatSend();
    });
  }

  if (btnAnalyze) {
    btnAnalyze.addEventListener('click', async () => {
      const nameEl = document.getElementById('strategist-business-name');
      const audienceEl = document.getElementById('strategist-target-audience');
      const bottleneckEl = document.getElementById('strategist-bottleneck');
      
      const name = nameEl ? nameEl.value.trim() : '';
      const audience = audienceEl ? audienceEl.value.trim() : '';
      const bottleneck = bottleneckEl ? bottleneckEl.value.trim() : '';

      if (!name || !audience || !bottleneck) {
        showToast("Please answer all operational queries first.", "warning");
        return;
      }

      btnAnalyze.disabled = true;
      btnAnalyze.textContent = "COMPILING MATRIX DIAGNOSTICS...";

      // Auth guard: must be logged in
      if (!isUserAuthenticated()) {
        btnAnalyze.disabled = false;
        btnAnalyze.textContent = "ANALYZE ENTERPRISE MATRIX";
        showToast("Please sign in to access the AI Strategist.", "warning");
        const authOverlay = document.getElementById('auth-modal-overlay');
        if (authOverlay) authOverlay.style.display = 'flex';
        return;
      }

      // Premium guard: check subscription
      const isPremiumOrTrial = state.user && (
        state.user.plan_type === 'Premium' ||
        state.user.plan_type === 'Trial' ||
        state.user.subscription?.plan === 'Premium' ||
        state.user.subscription?.plan === 'Trial'
      );
      if (!isPremiumOrTrial) {
        btnAnalyze.disabled = false;
        btnAnalyze.textContent = "ANALYZE ENTERPRISE MATRIX";
        showPricingModal(true);
        showToast("Premium or Trial plan required for AI Strategist.", "warning");
        return;
      }

      try {
        const data = await apiCall('/api/strategist/compile', {
          method: 'POST',
          body: JSON.stringify({
            businessName: name,
            targetAudience: audience,
            bottleneck: bottleneck
          })
        });

        btnAnalyze.disabled = false;
        btnAnalyze.textContent = "Re-Compile Matrix";

        if (data.success) {
          isAnalysisComputed = true;
          currentBusinessContext = { name, audience, bottleneck, strategy: data };
          strategistChatHistory = [
            { role: 'user', content: `Compile strategy for ${name} selling to ${audience} with bottleneck ${bottleneck}` },
            { role: 'assistant', content: `Analysis Compiled successfully.` }
          ];

          if (chatLogs) {
            chatLogs.innerHTML = '';
            const welcomeBubble = document.createElement('div');
            welcomeBubble.className = 'chat-bubble assistant';
            welcomeBubble.innerHTML = `<strong>Enterprise Analysis Compiled!</strong><br>I have generated a customized operational blueprint based on your query. Please review the <strong>7-tab Strategy Board</strong> below.<br><br>You can now ask follow-up questions in the chat bar below.`;
            chatLogs.appendChild(welcomeBubble);
          }

          const keys = ['analysis', 'opportunities', 'automation', 'marketing', 'leads', 'revenue', 'plan'];
          keys.forEach(k => {
            const tabPane = document.getElementById(`tab-out-${k}`);
            if (tabPane && data[k]) {
              tabPane.innerHTML = `<p>${data[k]}</p>`;
            }
          });

          if (outputPanel) outputPanel.style.display = 'block';
          showToast("Strategic analysis matrix compiled successfully!");
          
          if (data.quota) {
            showToast(`Remaining Daily Quota: ${data.quota.remaining}/${data.quota.limit}`, "info");
          }
        }
      } catch (err) {
        btnAnalyze.disabled = false;
        btnAnalyze.textContent = "ANALYZE ENTERPRISE MATRIX";
        console.error('[Strategist Compile Error]', err);
        // Show user-visible error unless apiCall already handled it (auth/403)
        if (err.message !== 'Unauthorized' && err.message !== 'Forbidden' && err.message !== 'No backend') {
          showToast("Analysis failed. Please check your connection and try again.", "error");
        }
      }
    });
  }

  loadLiveDashboardMetrics();
  loadLiveBusinessNews();

  // Prevent multiple intervals stacking by clearing any prior instance
  if (window.marketRefreshInterval) {
    clearInterval(window.marketRefreshInterval);
  }
  // Setup 60-second auto-refresh
  window.marketRefreshInterval = setInterval(() => {
    loadLiveDashboardMetrics();
  }, 60000);
}

// Global exposure for backwards compatibility
window.updateConversionFunnel = updateConversionFunnel;
window.loadLiveDashboardMetrics = loadLiveDashboardMetrics;
window.initExpandSection = initExpandSection;
