/* ==========================================================================
   AI-OS // ENTERPRISE LEGAL DOCUMENTATION DATABASE
   ========================================================================== */

const legalData = {
  terms: {
    title: "TERMS OF SERVICE AND SERVICE AGREEMENT",
    sections: [
      {
        heading: "1. BINDING AGREEMENT & ELIGIBILITY",
        text: "This Terms of Service and Service Agreement (the \"Agreement\") constitutes a legally binding contract between A.R. Labs (\"Company\", \"we\", \"us\", or \"our\") and the individual or legal entity accessing or using the AI-OS platform (\"User\", \"you\", or \"your\"). By accessing, deploying, compiling, or executing any workflow or prompt engineering protocol within the AI-OS suite, you represent and warrant that you possess the legal capacity to enter into this Agreement. If you are accepting this Agreement on behalf of a corporate entity, you represent that you have the explicit authority to bind such entity. If you do not agree to all terms and conditions set forth herein, you must immediately cease all access and utilization of the services."
      },
      {
        heading: "2. ACCEPTABLE USE & PLATFORM RESTRICTIONS",
        text: "Users are granted a limited, non-exclusive, non-transferable, revocable license to access the AI-OS platform for personal, educational, or commercial prototyping purposes. You agree to use the services in strict compliance with all applicable local, national, and international laws and regulations. Prohibited activities include, but are not limited to: (a) attempting to reverse engineer, decompile, or extract the source code or operational weights of any underlying model or platform infrastructure; (b) utilizing the AI prompt generation pipeline to draft, synthesize, or expand content that is unlawful, defamatory, profane, threatening, or designed to incite violence or discrimination; (c) introducing malicious software, viruses, or automation scripts to execute denial-of-service actions; and (d) systematically scraping or harvesting system logs, tool matrix configurations, or educational datasets without written authorization."
      },
      {
        heading: "3. INTELLECTUAL PROPERTY & PROMPT OWNERSHIP",
        text: "As between you and A.R. Labs, you retain all right, title, and interest in and to the input descriptions, scripts, or specifications you provide to the services (the \"User Input\"). Subject to your compliance with this Agreement, A.R. Labs hereby assigns to you all its rights, title, and interest in the prompt output generated by the AI-powered JSON Prompt Generator (the \"Generated Output\"). You acknowledge that due to the probabilistic nature of generative models, identical or similar inputs may yield identical or similar outputs across different users; A.R. Labs does not warrant or represent that the Generated Output is unique, nor does it guarantee trademark or copyright exclusivity for any visual designs, logos, or software specifications generated. All rights in the AI-OS platform architecture, styling assets, logo marks, and companion personality engines remain the exclusive property of A.R. Labs."
      },
      {
        heading: "4. LIMITATION OF LIABILITY & INDEMNIFICATION",
        text: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL A.R. LABS, ITS DIRECTORS, EMPLOYEES, PARTNERS, OR SUPPLIERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH: (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (II) ANY CONTENT OBTAINED FROM THE SERVICES; OR (III) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY. THE AGGREGATE LIABILITY OF A.R. LABS FOR ANY CLAIMS UNDER THIS AGREEMENT IS LIMITED STRICTLY TO THE FEES PAID BY YOU, IF ANY, TO THE COMPANY FOR THE SPECIFIC SERVICE IN DISPUTE. You agree to defend, indemnify, and hold harmless A.R. Labs from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including attorney's fees) arising from your violation of this Agreement or your misuse of the generated prompt assets."
      },
      {
        heading: "5. DISCLAIMER OF WARRANTIES",
        text: "THE AI-OS PLATFORM AND ALL GENERATED ASSETS ARE PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT. A.R. LABS DOES NOT WARRANT THAT: (A) THE SERVICES WILL RUN UNINTERRUPTED, SECURE, OR BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY ERRORS OR DEFECTS WILL BE CORRECTED IMMEDIATELY; (C) THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE RESULTS OF USING THE SERVICES WILL MEET YOUR TECHNICAL OR BUSINESS REQUIREMENTS."
      },
      {
        heading: "6. TERMINATION OF ACCOUNT & PLATFORM SUSPENSION",
        text: "A.R. Labs reserves the right, in its sole discretion and without prior notice or liability, to terminate or suspend your access to the platform immediately, including but not limited to, breaches of this Agreement, suspected fraudulent activity, or compliance with legal mandates. Upon termination, your right to use the platform services will cease immediately. All provisions of this Agreement which by their nature should survive termination shall survive, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability."
      },
      {
        heading: "7. GOVERNING LAW & EXCLUSIVE JURISDICTION",
        text: "<strong>These Terms, Conditions, Policies, Services, Products, Features, APIs, Content, and all interactions with this platform shall be governed and construed exclusively in accordance with the laws of the Republic of India. By accessing or using this website, the user irrevocably agrees that any dispute, claim, controversy, legal proceeding, arbitration, injunction, recovery action, contractual disagreement, statutory interpretation, tort claim, intellectual property dispute, consumer complaint, or any matter whatsoever arising directly or indirectly out of the use of this platform shall be subject solely and exclusively to the competent courts located in Indore, Madhya Pradesh, India. The user expressly waives any objection relating to territorial jurisdiction, venue inconvenience, or forum selection and agrees not to initiate or maintain any legal proceedings in any other jurisdiction, state, district, or country.</strong>"
      }
    ]
  },
  privacy: {
    title: "PRIVACY AND DATA PROTECTION POLICY",
    sections: [
      {
        heading: "1. PRIVACY COMMITMENT & DATA ARCHITECTURE",
        text: "A.R. Labs is committed to protecting the privacy of its users and maintaining absolute transparency regarding data handling. Our data architecture is designed under the principle of \"data minimization\" and \"privacy by design\". This policy outlines what information we collect, how it is processed, and the robust security protocols deployed to safeguard your personal space."
      },
      {
        heading: "2. LOCAL SPEECH PROCESSING & MICROPHONE PRIVACY",
        text: "A.R. Labs implements a strict local speech-to-text processing protocol for its Voice Input feature. When you engage the microphone button, all audio capture is processed locally on your client device using your browser's native Web Speech API (SpeechRecognition). **NO AUDIO RECORDINGS, VOICE BIOMETRICS, OR SPEECH FEEDS ARE TRANSMITTED, STORED, OR PROCESSED ON A.R. LABS SERVERS.** The microphone access is triggered exclusively upon your explicit interaction (clicking the mic button) and is shut down immediately when you cancel, retry, or stop speaking. The translated text transcript is inserted directly into your browser's input field for your review and editing before any external submission."
      },
      {
        heading: "3. DATA TRANSMISSION & THIRD-PARTY INTEGRATIONS",
        text: "When you request the generation of an intelligent JSON prompt, the text description in the input box is securely transmitted via TLS encryption to our server-side API, which communicates with the OpenRouter API to execute the Llama model prompt expansion. No personally identifiable information (PII) is attached to these prompts. For billing, subscription verification, and transaction processing, payment details are collected directly by secure third-party processors (PayPal, Razorpay) under their respective security policies. A.R. Labs does not store credit card or bank account information."
      },
      {
        heading: "4. COOKIE POLICY & LOCAL STORAGE USAGE",
        text: "AI-OS uses essential cookies and local browser storage (localStorage/sessionStorage) to maintain active user sessions, store your UI preferences (such as dark/light theme setting), track favorite tools, and manage the comparison checklist dashboard. These technologies are crucial for performance and local state restoration. We do not use tracking or advertising cookies to profile your behavior across third-party websites."
      },
      {
        heading: "5. DATA RETENTION & ACCOUNT SEGREGATION",
        text: "User profile records (including nicknames, token balances, and transaction references) are stored securely in Supabase database infrastructure. Profile metadata is retained as long as your account remains active. Users may request the deletion of their profile metadata, transaction references, or token ledger records at any time by contacting our data protection representative. Deleted records are purged from active operational tables within 30 days."
      },
      {
        heading: "6. DATA SECURITY PRACTICES",
        text: "We implement industry-standard administrative, technical, and physical security measures to protect your database profiles from unauthorized access, modification, disclosure, or destruction. Access to user records is strictly restricted to authorized system daemons. While we strive to deploy maximum grade security practices, no method of transmission or electronic storage is 100% secure, and we cannot guarantee absolute database security."
      },
      {
        heading: "7. GOVERNING LAW & EXCLUSIVE JURISDICTION REFERENCE",
        text: "This Privacy Policy and all matters relating to data collection, user privacy, compliance, and regulatory protection shall be governed exclusively by the laws of the Republic of India. For the avoidance of doubt, any dispute, controversy, or claim arising under or in connection with this Privacy Policy or our data practices shall be resolved exclusively in the competent courts located in Indore, Madhya Pradesh, India, in accordance with the jurisdictional mandates set forth in the Terms of Service."
      }
    ]
  },
  aiUsage: {
    title: "RESPONSIBLE AI AND ALGORITHMIC USAGE POLICY",
    sections: [
      {
        heading: "1. INTENDED USE & RESPONSIBLE PROMPT ENGINEERING",
        text: "The AI-OS Intelligent Prompt Generator is engineered to translate natural language ideas into structured JSON instructions optimized for creative generative tools. Users must engage with the prompt generation pipeline responsibly. Prompt engineering techniques designed to bypass model guardrails (commonly referred to as \"jailbreaking\" or \"prompt injection\") to generate harmful, illegal, or abusive content are strictly prohibited."
      },
      {
        heading: "2. GENERATED CONTENT DISCLAIMER & OVERSIGHT",
        text: "The prompt payloads generated by the Llama-powered AI engine represent suggestions for creative enhancement. The user bears sole responsibility for reviewing, validating, and auditing all generated prompt instructions before utilizing them in final production environments. A.R. Labs does not review or edit prompt outputs, and makes no representations regarding the safety, legality, or suitability of generated prompts for external platforms."
      },
      {
        heading: "3. PROMPT OWNERSHIP AND COPYRIGHT STATUS",
        text: "A.R. Labs claims no ownership rights over the prompt structures, JSON keys, or expanded descriptions generated by the AI-OS application. You retain full copyright ownership of the outputs to the extent permitted by intellectual property law. A.R. Labs grants you a perpetual, royalty-free, worldwide license to copy, adapt, modify, and distribute the JSON output templates in your software projects, branding campaigns, and media productions."
      },
      {
        heading: "4. ABUSE FILTERING & CONTENT MODERATION",
        text: "While our backend API passes user text directly to the model using TLS connections, the OpenRouter API and underlying Llama model may contain built-in safety filters that refuse to process descriptions containing profane, sexually explicit, or violent language. A.R. Labs reserves the right to log failed generation requests and block users who repeatedly attempt to bypass content restrictions to generate malicious material."
      }
    ]
  },
  disclaimer: {
    title: "DISCLAIMER OF WARRANTIES AND LIMITATION STATEMENT",
    sections: [
      {
        heading: "1. NO GUARANTEE OF SYSTEM ACCURACY OR FIT",
        text: "THE OUTPUT GENERATED BY THE AI-OS PROMPT GENERATION SUITE IS THE PRODUCT OF PROBABILISTIC MACHINE LEARNING MODELS. A.R. LABS OFFERS NO GUARANTEE, WARRANTY, OR REPRESENTATION THAT THE EXPANDED DESCRIPTIONS OR STRUCTURED JSON PAYLOADS WILL OPERATE CORRECTLY, GENERATE ACCURATE IMAGES, COMPILE WITHOUT PROGRAMMING ERRORS, OR FIT THE INTENDED TECHNICAL OR BUSINESS PURPOSES. AI OUTPUTS ARE HIGHLY VARIABLE AND SUBJECT TO FLUCTUATIONS IN RESOLUTION ACCURACY."
      },
      {
        heading: "2. EDUCATIONAL & PROTOTYPING PURPOSE LIMITATION",
        text: "All AI-OS roadmaps, tool recommendations, workflow timelines, and master prompt configurations are designed solely for educational, reference, and rapid prototyping purposes. The information provided on this platform does not constitute professional software architecture, engineering, industrial design, legal, or financial advice. Users must perform independent verification and secure professional audits before placing generated designs or software components into live production environments."
      },
      {
        heading: "3. INDEPENDENT THIRD-PARTY TOOL RELATIONSHIP",
        text: "A.R. Labs maintains no official affiliation, sponsorship, endorsement, or commercial partnership with the recommended third-party AI platforms (including Canva, Suno, Flow AI, Flux AI, ElevenLabs, OpenAI, Google Labs, or OpenRouter). All trademarks, product names, logos, and links cited within the AI-OS roadmap database remain the exclusive property of their respective owners. Accessing recommended tools and deploying generated prompts inside their systems remains subject to the respective terms and conditions of those third-party providers."
      },
      {
        heading: "4. JURISDICTION & GOVERNING LAW",
        text: "All disclaimers, liability limitations, and warranty exclusions contained herein shall be governed and interpreted exclusively in accordance with the laws of the Republic of India. Any litigation, arbitration, or legal action arising out of or related to this Disclaimer or your use of the platform's outputs shall be brought solely and exclusively in the competent courts of Indore, Madhya Pradesh, India."
      }
    ]
  },
  userAgreement: {
    title: "END USER LICENSE AND USER AGREEMENT",
    sections: [
      {
        heading: "1. PLATFORM LICENSE & SCOPE",
        text: "This End User License and User Agreement is a legal contract between you and A.R. Labs governing your usage of the AI-OS platform. We grant you a limited, non-exclusive, non-transferable, revocable license to access and interact with the AI-OS orchestration suite for personal and professional software prototyping."
      },
      {
        heading: "2. ACCOUNT CONDITIONS & USAGE TERMS",
        text: "You agree to provide true and accurate information during configuration and session restoration. You remain solely responsible for any generated prompts, system calls, API usage, and the integration of generated code in external systems."
      },
      {
        heading: "3. GOVERNING LAW & EXCLUSIVE JURISDICTION",
        text: "This User Agreement and all obligations, actions, or disputes arising hereunder shall be governed by and construed in accordance with the laws of the Republic of India. Any dispute, litigation, or legal proceeding concerning this agreement, the license, or the usage of the platform shall be submitted exclusively to the jurisdiction of the competent courts in Indore, Madhya Pradesh, India. The user waives any claims of forum non-conveniens."
      }
    ]
  },
  legalNotice: {
    title: "CORPORATE REGULATORY & LEGAL NOTICE",
    sections: [
      {
        heading: "1. INTELLECTUAL PROPERTY & PATENTS NOTICE",
        text: "All proprietary software architectures, workflow compiling engines, design systems, visual tokens, and graphical interfaces presented within the AI-OS framework are the protected intellectual property of A.R. Labs. Unauthorized reproduction or reverse engineering of these modules is strictly prohibited under international copyright laws."
      },
      {
        heading: "2. REGULATORY & EXCLUSIVE JURISDICTION NOTICE",
        text: "These Terms, Conditions, Policies, Services, Products, Features, APIs, Content, and all interactions with this platform shall be governed and construed exclusively in accordance with the laws of the Republic of India. By accessing or using this website, the user irrevocably agrees that any dispute, claim, controversy, legal proceeding, arbitration, injunction, recovery action, contractual disagreement, statutory interpretation, tort claim, intellectual property dispute, consumer complaint, or any matter whatsoever arising directly or indirectly out of the use of this platform shall be subject solely and exclusively to the competent courts located in Indore, Madhya Pradesh, India. The user expressly waives any objection relating to territorial jurisdiction, venue inconvenience, or forum selection and agrees not to initiate or maintain any legal proceedings in any other jurisdiction, state, district, or country."
      }
    ]
  },
  cookiePolicy: {
    title: "COOKIE AND LOCAL STORAGE POLICY",
    sections: [
      {
        heading: "1. COOKIE USAGE & SESSION MANAGEMENT",
        text: "We utilize essential cookies, session storage, and local storage (localStorage/sessionStorage) to facilitate user authentication, store selected configuration drop-downs, customize UI themes, and track favorite node indicators. These technical cookies are strictly necessary for the proper rendering and speed of the platform."
      },
      {
        heading: "2. REFUSAL AND DELETION PROCEDURES",
        text: "Users can manage cookie preferences directly through their web browser settings. Disabling cookies may limit the availability of some interactive components, including wizard state tracking and saved roadmaps."
      },
      {
        heading: "3. JURISDICTION & POLICY COMPLIANCE",
        text: "This Cookie Policy and any related compliance disputes shall be governed by the laws of the Republic of India. Any legal actions or challenges concerning cookie usage, user storage data, or tracking practices shall fall under the exclusive jurisdiction of the competent courts of Indore, Madhya Pradesh, India."
      }
    ]
  }
};
